name: cs5670_python_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib=2.2.3
  - numpy=1.16.0
  - opencv=3.4.2
  - pillow=6.2.0
  - python=3.7.9
  - scipy=1.2.0
  - nose=1.3.7
  - imageio=2.8.0

